import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/vazirmatn/400.css";

export const metadata: Metadata = {
  title: "Testing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="antialiased bg-gray-50">{children}</body>
    </html>
  );
}
